# Python Numpy Tutorial for Beginners
## https://www.youtube.com/watch?v=QUT1VHiLmmI



Numpy is a multidimensional array library - 1D, 2D, 3D ... nD
Lists are slow to access, whereas numpy is fast.
Numpy uses fixed type data types IE a number is a number of int32 type (32 bits or 4bytes). Whereas the same number in a list in python is represented by 4 different categories (size, reference count, object type and object value totalling 28 bytes or 224 bits).<br>
It's therefore faster to read arrays, and there's is no type checking when iterating through arrays.<br>
Numpy also uses contiguous memory, IE all the memory is in a straight line and next to each other. The same structure in a list would store the data all over the place.<br>


In [2]:
import numpy as np

## The Basics

In [3]:
# Create 1D array
a = np.array([1,2,3], dtype= 'int16')
print(a)

[1 2 3]


In [4]:
# Create 2D array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]], dtype= 'int32')
print(b)

[[9 8 7]
 [6 5 4]]


In [5]:
# Get the depth/dimension of the array
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get the shape of the array
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Get type
a.dtype

dtype('int16')

In [8]:
# Get size (ie size of array)
print(a.itemsize)
print(b.itemsize)

2
4


In [9]:
# Get memory size
print(a.nbytes)
print(b.nbytes)


6
24


## Accessing/Changing specific elements in multidimensional arrays

In [11]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


To get a specific element in a multidimensional array use the [row-index, column-index] notation. All the same python list index/splicing methods work

In [12]:
# return the value 13 from the array a
a[1, 5]

13

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column ::--> : will get all of the rows, and the column index will return the 3rd column
a[:, 2]

array([ 3, 10])

In [17]:
# More complex slicing [start-index : end-index : stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [18]:
# 3D example
b= np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
#Return the value 4
# Tip is to work outside in
b[0, 1, 1]

4

In [28]:
# Replace index values
b[:, 1, :] # selects all rows, first index in each block, all items from the specific index
b[:, 1, :] = [[9, 9], [8, 8]] # replaces selected index with 99 & 88, replacement must be same size of replacee
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different arrays

In [30]:
# All 0-matrix
np.zeros((2,3,3)) # 2 outside blocks of 3 rows and 3 columns

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# 1s matrix, specialising dtype of int32
np.ones((4, 3, 2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [32]:
# Any other number
np.full((2,2,3), 69, dtype= 'int16')

array([[[69, 69, 69],
        [69, 69, 69]],

       [[69, 69, 69],
        [69, 69, 69]]], dtype=int16)

In [34]:
# Random numbers
np.random.rand(4, 3) # creates array of 4 rows 3 columns

array([[0.97919562, 0.9219305 , 0.25092416],
       [0.48636687, 0.34817733, 0.97349086],
       [0.70589342, 0.60190011, 0.08407235],
       [0.79679794, 0.91095296, 0.39542348]])

In [44]:
#Random integers
np.random.randint(1, 50, size= (3, 3))

array([[21, 33, 43],
       [35, 16, 12],
       [25, 37,  8]])

In [45]:
# Creates an identity matrix or a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Task1: Create the following array



In [64]:
my_array = np.full((5, 5), 1, dtype= 'int8')
my_array[1, 1:4] = [0,0,0]
my_array[2, 1:4] = [0,9,0]
my_array[3, 1:4] = [0,0,0]
my_array


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [72]:
# Model answer
# create 5x5 matrix filled with onesKey K
output = np.ones((5, 5))
# create 3X3 matrix filled with 0
zeros = np.zeros((3, 3))
zeros[1, 1] = 9
#joining the two
output[1:-1, 1:-1] = zeros
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Note when copying arrays!!!

In [78]:
a = np.array([1,2,3])
b = a #numpy uses a pointer to point to the item a
b[0] = 100 # the pointer points to b and a
print(b)
print(a) # array a is changed by the above

[100   2   3]
[100   2   3]


In [79]:
c = np.array([4, 5, 6])
d = c.copy()
d[0] = 99
print(d)
print(c) 

[99  5  6]
[4 5 6]


## Mathematic functions

In [82]:
a = np.array([1, 2, 3, 4])
a += 2
a

array([3, 4, 5, 6])

In [83]:
a *= 2
a

array([ 6,  8, 10, 12])

In [87]:
a //= 2
a

array([1, 2, 2, 3])