# Python Numpy Tutorial for Beginners
## https://www.youtube.com/watch?v=GB9ByFAIAH4



Numpy is a multidimensional array library - 1D, 2D, 3D ... nD
Lists are slow to access, whereas numpy is fast.
Numpy uses fixed type data types IE a number is a number of int32 type (32 bits or 4bytes). Whereas the same number in a list in python is represented by 4 different categories (size, reference count, object type and object value totalling 28 bytes or 224 bits).<br>
It's therefore faster to read arrays, and there's is no type checking when iterating through arrays.<br>
Numpy also uses contiguous memory, IE all the memory is in a straight line and next to each other. The same structure in a list would store the data all over the place.<br>


In [2]:
import numpy as np

## The Basics

In [3]:
# Create 1D array
a = np.array([1,2,3], dtype= 'int16')
print(a)

[1 2 3]


In [4]:
# Create 2D array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]], dtype= 'int32')
print(b)

[[9 8 7]
 [6 5 4]]


In [5]:
# Get the depth/dimension of the array
print(a.ndim)
print(b.ndim)

1
2


In [6]:
# Get the shape of the array
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
# Get type
a.dtype

dtype('int16')

In [8]:
# Get size (ie size of array)
print(a.itemsize)
print(b.itemsize)

2
4


In [9]:
# Get memory size
print(a.nbytes)
print(b.nbytes)


6
24


## Accessing/Changing specific elements in multidimensional arrays

In [11]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


To get a specific element in a multidimensional array use the [row-index, column-index] notation. All the same python list index/splicing methods work

In [12]:
# return the value 13 from the array a
a[1, 5]

13

In [13]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
# Get a specific column ::--> : will get all of the rows, and the column index will return the 3rd column
a[:, 2]

array([ 3, 10])

In [17]:
# More complex slicing [start-index : end-index : stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [18]:
# 3D example
b= np.array([[[1, 2], [3,4]], [[5,6], [7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
#Return the value 4
# Tip is to work outside in
b[0, 1, 1]

4

In [28]:
# Replace index values
b[:, 1, :] # selects all rows, first index in each block, all items from the specific index
b[:, 1, :] = [[9, 9], [8, 8]] # replaces selected index with 99 & 88, replacement must be same size of replacee
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initialising different arrays

In [30]:
# All 0-matrix
np.zeros((2,3,3)) # 2 outside blocks of 3 rows and 3 columns

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [31]:
# 1s matrix, specialising dtype of int32
np.ones((4, 3, 2), dtype='int32')

array([[[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1],
        [1, 1]]])

In [32]:
# Any other number
np.full((2,2,3), 69, dtype= 'int16')

array([[[69, 69, 69],
        [69, 69, 69]],

       [[69, 69, 69],
        [69, 69, 69]]], dtype=int16)

In [34]:
# Random numbers
np.random.rand(4, 3) # creates array of 4 rows 3 columns

array([[0.97919562, 0.9219305 , 0.25092416],
       [0.48636687, 0.34817733, 0.97349086],
       [0.70589342, 0.60190011, 0.08407235],
       [0.79679794, 0.91095296, 0.39542348]])

In [44]:
#Random integers
np.random.randint(1, 50, size= (3, 3))

array([[21, 33, 43],
       [35, 16, 12],
       [25, 37,  8]])

In [45]:
# Creates an identity matrix or a square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Task1: Create the following array



In [64]:
my_array = np.full((5, 5), 1, dtype= 'int8')
my_array[1, 1:4] = [0,0,0]
my_array[2, 1:4] = [0,9,0]
my_array[3, 1:4] = [0,0,0]
my_array


array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [72]:
# Model answer
# create 5x5 matrix filled with onesKey K
output = np.ones((5, 5))
# create 3X3 matrix filled with 0
zeros = np.zeros((3, 3))
zeros[1, 1] = 9
#joining the two
output[1:-1, 1:-1] = zeros
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## Note when copying arrays!!!

In [78]:
a = np.array([1,2,3])
b = a #numpy uses a pointer to point to the item a
b[0] = 100 # the pointer points to b and a
print(b)
print(a) # array a is changed by the above

[100   2   3]
[100   2   3]


In [79]:
c = np.array([4, 5, 6])
d = c.copy()
d[0] = 99
print(d)
print(c) 

[99  5  6]
[4 5 6]


## Mathematic functions
https://numpy.org/doc/stable/reference/routines.html

In [82]:
a = np.array([1, 2, 3, 4])
a += 2
a

array([3, 4, 5, 6])

In [83]:
a *= 2
a

array([ 6,  8, 10, 12])

In [87]:
a //= 2
a

array([1, 2, 2, 3])

## Linear Algebra/Matrix Multiplication


In [90]:
# matrix multiplication
a = np.ones((2,4))
b = np.full((4,2), 2)
np.matmul(a, b)

array([[8., 8.],
       [8., 8.]])

In [92]:
# determinant
c = np.identity(3)
np.linalg.det(c)

1.0

## Statistics

In [100]:
stats = np.array([[1,2,3], [4,5,2]])
stats

array([[1, 2, 3],
       [4, 5, 2]])

In [98]:
#min/max
np.max(stats)
np.min(stats)

1

In [103]:
#row -(0) or column (1) based -> returns the min/max value of each space in the array along the row/column
np.max(stats, axis= 1)
np.min(stats, axis= 0)

array([1, 2, 2])

In [106]:
# aggregation -> by row will add the elements per row position, by column will add the rows together
np.sum(stats, axis= 1)

array([ 6, 11])

## Reorganizing arrays

In [111]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)
after = before.reshape((2, 2, 2)) # reshapes the matrix as long as the number of index positions are the same
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [116]:
# vertically stacking vectors/matrixes
v1 = np.random.randint(1, 20, size= (4))
v2 = np.random.randint(1, 17, size= (4))
print(v1, v2)
np.vstack([v1, v2])

[ 3 16  5 15] [14 16 10 10]


array([[ 3, 16,  5, 15],
       [14, 16, 10, 10]])

In [120]:
#horizontal stacks
h1 = np.random.randint(1, 7, size= (4))
h2 = np.random.randint(2, 9, size= (4))
print(h1, h2)
np.hstack([h1, h2, h1, h2])

[6 3 3 6] [8 7 2 4]


array([6, 3, 3, 6, 8, 7, 2, 4, 6, 3, 3, 6, 8, 7, 2, 4])

## Miscellaneous
### Loading data from file

In [124]:
# import from external source, & change datatype
data_csv = np.genfromtxt('numpyData.csv', delimiter=',')
data_csv = data_csv.astype('int32')
data_csv

array([[41, 23, 14, 50, 30],
       [20, 10, 41, 49,  7],
       [43, 19, 39, 43,  4],
       [ 8,  5, 25, 24, 25],
       [15, 31, 10, 12,  8],
       [23, 13, 44, 13, 40],
       [29, 46, 22,  4, 45],
       [32,  3, 26, 46, 16],
       [28, 38, 21,  8,  2],
       [32, 37, 16, 24, 24]])

### Boolean masking and advanced Indexing

In [125]:
data_csv < 24 # bool masking

array([[False,  True,  True, False, False],
       [ True,  True, False, False,  True],
       [False,  True, False, False,  True],
       [ True,  True, False, False, False],
       [ True, False,  True,  True,  True],
       [ True,  True, False,  True, False],
       [False, False,  True,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True,  True,  True],
       [False, False,  True, False, False]])

In [126]:
data_csv[data_csv > 4] #returns an array with the specific bool

array([41, 23, 14, 50, 30, 20, 10, 41, 49,  7, 43, 19, 39, 43,  8,  5, 25,
       24, 25, 15, 31, 10, 12,  8, 23, 13, 44, 13, 40, 29, 46, 22, 45, 32,
       26, 46, 16, 28, 38, 21,  8, 32, 37, 16, 24, 24])

In [141]:
data_csv[[0, 1],[1,0]]

array([23, 20])

## Task: 2

In [157]:
task_array = np.arange(1, 31, 1)
task_array = np.vstack((task_array[0:5], task_array[5:10], task_array[10:15], task_array[15:20], task_array[20:25], task_array[25:30]))
task_array

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [166]:
task_array[2:4, 0:2]

array([[11, 12],
       [16, 17]])

In [167]:
task_array[[0,1,2,3], [1, 2, 3, 4]]

array([ 2,  8, 14, 20])

In [183]:
task_array[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])