### Python Numpy Tutorial for Beginners
#### https://www.youtube.com/watch?v=QUT1VHiLmmI



Numpy is a multidimensional array library - 1D, 2D, 3D ... nD
Lists are slow to access, whereas numpy is fast.
Numpy uses fixed type data types IE a number is a number of int32 type (32 bits or 4bytes). Whereas the same number in a list in python is represented by 4 different categories (size, reference count, object type and object value totalling 28 bytes or 224 bits).<br>
It's therefore faster to read arrays, and there's is no type checking when iterating through arrays.<br>
Numpy also uses contiguous memory, IE all the memory is in a straight line and next to each other. The same structure in a list would store the data all over the place.<br>


In [1]:
import numpy as np

The Basics

In [14]:
# Create 1D array
a = np.array([1,2,3], dtype= 'int16')
print(a)

[1 2 3]


In [15]:
# Create 2D array
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]], dtype= 'int32')
print(b)

[[9 8 7]
 [6 5 4]]


In [16]:
# Get the depth/dimension of the array
print(a.ndim)
print(b.ndim)

1
2


In [17]:
# Get the shape of the array
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [18]:
# Get type
a.dtype

dtype('int16')

In [20]:
# Get size (ie size of array)
print(a.itemsize)
print(b.itemsize)

2
4


In [23]:
# Get memory size
print(a.nbytes)
print(b.nbytes)


6
24
